apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: import-images
  labels:
    generated-by: seed-job
spec:
  concurrencyPolicy: Forbid
  schedule: '0 */4 * * *'
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: import-images
          labels:
            generated-by: seed-job
        spec:
          containers:
          - name: import-images
            image: docker-registry.default.svc:5000/ci/ci-image
            command:
              - make
              - import-images
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi
          restartPolicy: OnFailure
          serviceAccount: ci-runner
          serviceAccountName: ci-runner
          terminationGracePeriodSeconds: 1
