apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: prune
  labels:
    generated-by: seed-job
spec:
  concurrencyPolicy: Forbid
  schedule: '0 */8 * * *'
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: pruner
          labels:
            generated-by: seed-job
        spec:
          containers:
          - name: pruner
            image: docker-registry.default.svc:5000/gitea/drone-base
            command:
              - make
              - prune
          restartPolicy: OnFailure
          serviceAccount: drone-agent
          serviceAccountName: drone-agent
          terminationGracePeriodSeconds: 1
