apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: save-cluster-state
  labels:
    generated-by: seed-job
spec:
  concurrencyPolicy: Forbid
  schedule: '0 */8 * * *'
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: saver
          labels:
            generated-by: seed-job
        spec:
          containers:
          - name: saver
            image: docker-registry.default.svc:5000/ci/ci-image
            command:
              - make
              - save-cluster-state
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi
          restartPolicy: OnFailure
          serviceAccount: ci-runner
          serviceAccountName: ci-runner
          terminationGracePeriodSeconds: 1
