apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: trigger-builds
  labels:
    generated-by: seed-job
spec:
  concurrencyPolicy: Forbid
  schedule: '0 */8 * * *'
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: pruner
          labels:
            generated-by: seed-job
        spec:
          containers:
          - name: pruner
            image: docker-registry.default.svc:5000/ci/ci-image
            command:
              - make
              - trigger-builds
          restartPolicy: OnFailure
          serviceAccount: ci-runner
          serviceAccountName: ci-runner
          terminationGracePeriodSeconds: 1
