apiVersion: batch/v1
kind: Job
metadata:
  labels:
    last-run: sep-03-2019-10-32
  name: seed-job
  namespace: ci
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: seed-job
      name: seed
    spec:
      containers:
      - command:
        - make
        - seed
        image: docker-registry.default.svc:5000/ci/ci-image
        imagePullPolicy: Always
        name: seed
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ci-runner
      serviceAccountName: ci-runner
      terminationGracePeriodSeconds: 1
