apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: import-images
spec:
  tasks:
    - name: import
      taskRef:
        name: ci
      params:
        - name: TARGET
          value: import-images
